---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cp-test-pvc
  labels:
    app: testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: mynfs
